### ISSUE TITLE
Firewall rule contract

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/openst-contracts#193] opened 2019-04-09 14:11 UTC
## User Story
As an economy
I want to forbid transactions that origin from anywhere else but my official mobile application
Because I want users to spend as much time as possible within my app.

### Scenario 1
Given that I am using the official mobile application of the economy
When I make a token transfer to another user via a registered rule
Then the token transfer is carried out (using rules and `TokenRules`).

We call these transactions *internal* from here on out.

### Scenario 2
Given that I am **not** using the official mobile application (e.g. MetaMask independently)
When I make a token transfer to another user via a registered rule
Then the token transfer is not possible.

We call these transactions *external* from here on out.

### Assumptions
1. Any economy should be able to prevent external transactions.
2. It should later be possible to remove the restriction.

### Observations
1. The restriction must be done on-chain. Any restriction at a higher level cannot be enforced on-chain and can therefore be circumvented.
2. Requires a whitelist to allow actors. A blacklist could not capture all possible invalid actors unless it exists of almost all possible addresses, which is a huge space.

### Options
1. Restrict base coins.
    * Is very hard to enforce. It would be easy for a single bad actor to provide base coins to a potential attacker.
2. Firewall.
    * An on-chain firewall that restricts transactions to be made by a list of known actors.
    * Whitelist must be managed on-chain.
    * Firewall must be enforced by the rules or `TokenRules` to ensure enforcement. Any higher layer *on-chain* would potentially allow an attacker to circumvent the firewall (on-chain) and execute rules.

### Firewall
We decided to have the firewall at the level of rules.

We decided against `TokenRules` to include a firewall, as we want to be able to have firewalled and non-firewalled rules registered in the `TokenRules` contract.

We decided against a `Firewall` rule as last rule before `TokenRules` in a chain of rules. The problem with this approach is that all rules would need to be registered in the Firewall rule in order to know the allowed rules. As the firewall would be the only rule registered with `TokenRules`, the registry needs to move into the firewall, which would lead to fuzzy responsibilities of classes.
Furthermore, in the specific case of credit, the firewall would be passed multiple times for a single utility token transfer. This means additional external calls and sender verification in a single transaction.

The firewall will be on a per-rule basis. Any rule can be a firewalled rule which would mean that `tx.origin` must always be a registered relayer (in our case a registered organization worker).

This way, by making the rules firewalled, only relayers which are registered organization workers can relay transactions. This means that meta-transactions can be guarded at the relayer level. The relayers can authenticate a meta-transaction to be originating from within the economy's official mobile application.

**Cost**
The cost of the modifier
```solidity
modifier firewalled() {
    if (firewallOn) {
      require(tx.origin == allowedSender, 'du kommst hier net rein');  
    }
    
    _;
}
```
is `<600 gas` if the firewall is on and `<300 gas` if the firewall is off.

## Implementation
* Create an abstract `Firewall` contract that:
    * Takes an `Organization` in the contsructor.
    * Provides a modifier `firewalled` which allows only workers to be **`tx.origin`**.
    * Provides a function with an `onlyOrganization` modifier to disable the firewall (`firewalled` allows calls from any transaction origin). 🚧 Do we really want this or would we rather replace the firewalled rules with non-firewalled pendants? 🚧
* Create an abstract `BaseRule` contract that extends `Firewall` and (🚧  @benjaminbollen help me out what was the other contract it should extend? 🚧)
* Every rule that should be firewalled must extend the firewall rule.

**Comment by schemar** [comment] 2019-04-09 15:36
Please also have a look at TypeChain

**Comment by schemar** [comment] 2019-04-17 10:26
Technically, a firewall rule binds the rules to be used by the designated *relayers,* not mobile application. The concern of mobile app restriction is then pushed to the relayer level. Relayers could in theory still decide to accept and relay any messages.

However, as the relayers are run by centralized parties as opposed to an open blockchain system, applications can decide to run specific relayers with specific rules.

1. How are relayers whitelisted? "Database" contract with restricted writing rights?
2. How to ensure that all deployed rules use the firewall rule(s) instead of the transfer rule(s) directly?

I still need to learn more about "safe", rules, and how everything interacts. I will go through the code in https://github.com/OpenST/openst-contracts

**Comment by schemar** [comment] 2019-04-17 16:48
Updated below in https://github.com/OpenST/openst-contracts/issues/193#issuecomment-484552869

**Comment by abhayks1** [comment] 2019-04-18 12:18
Nice description of the epic 💯.   Few comments and questions:

- A rule can have multiple methods which does token transfer. The modifier ```firewalled``` is applied at method level. It's possible that method m1 of Rule R1 is ```firewalled``` while method m2 of Rule R1 is not firewalled. Is this expected behaviour?

- It's more of a implementation detail. Since Firewall contract adds an extra layer/checks in token transfer(e.g. in PricerRule.pay) we should evaluate how much extra gas it will add on the rule transactions.

- ```Firewall must be enforced by the rules or TokenRules to ensure enforcement.```
I didn't get how Firewall contract and TokenRules contract will interact? 
I may be missing the point here 🤔

**Comment by schemar** [comment] 2019-04-18 13:21
> Nice description of the epic 💯. Few comments and questions:
> 
> * A rule can have multiple methods which does token transfer. The modifier `firewalled` is applied at method level. It's possible that method m1 of Rule R1 is `firewalled` while method m2 of Rule R1 is not firewalled. Is this expected behaviour?

Yes, it is possible. I don't think this is the expected behaviour. However, I also don't know how to enforce application of the firewall.

> * It's more of a implementation detail. Since Firewall contract adds an extra layer/checks in token transfer(e.g. in PricerRule.pay) we should evaluate how much extra gas it will add on the rule transactions.

It *should* be very low as it is two `==` checks (`firewall active?` and `tx.origin allowed?`)

>> * Firewall must be enforced by the rules or `TokenRules` to ensure enforcement.
> 
> I didn't get how Firewall contract and TokenRules contract will interact?
> I may be missing the point here 🤔

The idea right now is that the rules will get the firewall. Rules call eventually on the TokenRules to execute a transfer.

**Comment by schemar** [comment] 2019-04-18 15:15
# UPDATED

## User Story
As an economy
I want to forbid transactions that origin from anywhere else but my official mobile application
Because I want users to spend as much time as possible within my app.

## Scenarios
### Scenario 1
Given that I am using the official mobile application of the economy
When I make an allowed token transfer to another user
Then the token transfer is carried out (using rules and `TokenRules`).

We call these transactions *internal* from here on out.

### Scenario 2
Given that I am **not** using the official mobile application (e.g. MetaMask independently)
When I make an allowed token transfer to another user
Then the token transfer is not possible.

We call these transactions *external* from here on out.

## More Info

### Assumptions
1. Any economy should be able to prevent external transactions.
2. It should later be possible to remove the restriction.

### Observations
1. The restriction must be done on-chain. Any restriction at a higher level cannot be enforced on-chain and can therefore be circumvented.
2. Requires a whitelist to allow actors. A blacklist could not capture all possible invalid actors unless it exists of almost all possible addresses, which is a huge space.

### Options
1. Restrict base coins.
    * Is very hard to enforce. It would be easy for a single bad actor to provide base coins to a potential attacker.
2. Firewall.
    * An on-chain firewall that restricts transactions to be made by a list of known actors.
    * Whitelist must be managed on-chain.
    * Firewall must be enforced by the rules or `TokenRules` to ensure enforcement. Any higher layer *on-chain* would potentially allow an attacker to circumvent the firewall (on-chain) and execute rules.

### Firewall
We decided to have the firewall at the level of rules.

We decided against `TokenRules` to include a firewall, as we want to be able to have firewalled and non-firewalled rules registered in the `TokenRules` contract.

We decided against a `Firewall` rule as last rule before `TokenRules` in a chain of rules. The problem with this approach is that all rules would need to be registered in the Firewall rule in order to know the allowed rules. As the firewall would be the only rule registered with `TokenRules`, the registry needs to move into the firewall, which would lead to fuzzy responsibilities of classes.
Furthermore, in the specific case of credit, the firewall would be passed multiple times for a single utility token transfer. This means additional external calls and sender verification in a single transaction.

The firewall will be on a per-rule basis. Any rule can be a firewalled rule which would mean that `tx.origin` must always be a registered relayer (in our case a registered organization worker).

This way, by making the rules firewalled, only relayers which are registered organization workers can relay transactions. This means that meta-transactions can be guarded at the relayer level. The relayers can authenticate a meta-transaction to be originating from within the economy's official mobile application.

**Cost**
The cost of the modifier
```solidity
modifier firewalled() {
    if (firewallOn) {
      require(tx.origin == allowedSender, 'du kommst hier net rein');  
    }
    
    _;
}
```
is `<600 gas` if the firewall is on and `<300 gas` if the firewall is off.

## Implementation
* Create an abstract `Firewall` contract that:
    * Takes an `Organization` in the contsructor.
    * Provides a modifier `firewalled` which allows only workers to be **`tx.origin`**.
    * Provides a function with an `onlyOrganization` modifier to disable the firewall (`firewalled` allows calls from any transaction origin). 🚧 Do we really want this or would we rather replace the firewalled rules with non-firewalled pendants? 🚧
* Create an abstract `BaseRule` contract that extends `Firewall` and (🚧  @benjaminbollen help me out what was the other contract it should extend? 🚧)
* Every rule that should be firewalled must extend the firewall rule.

## Call To Action
🐙 Please 🐙 
* Think of more assumptions.
* Think of more observations.
* **Think of more options.**
* Argue for and against any of the options.
* Improve all the sections. **Especially the firewall and implementation.**

/cc @benjaminbollen @pgev

**Comment by schemar** [comment] 2019-04-23 14:08
Updated the description and added the first sub-task (user story).

**Comment by abhayks1** [comment] 2019-04-23 14:32
Since the firewall contract will be integrated with multiple rules contract, I also suggest to have FirewallInterface contract. This can be a separate ticket. @schemar what do you think?

**Comment by schemar** [comment] 2019-04-23 14:48
In addition to the abstract class? Why?

**Comment by 0xsarvesh** [comment] 2019-04-24 11:38
> Scenario 2
Given that I am not using the official mobile application (e.g. MetaMask independently)
When I make an allowed token transfer to another user
Then the token transfer is not possible.

`TokenRules` also needs to extend `BaseRule` -> `Firewall` because of direct transfer. 

https://github.com/OpenST/openst-contracts/blob/800b0d209e7cc164841b35720bd536fd6170c1f9/contracts/token/TokenRules.sol#L261

**Comment by schemar** [comment] 2019-04-24 11:42
`TokenRules` shouldn't be firewalled itself. It can only be called by registered rules, and the registered rules should be firewalled.

**Comment by schemar** [comment] 2019-04-24 11:44
Ah I get your question. What if we want to firewall direct transfers? I think that is not considered at the moment. @benjaminbollen / @pgev ? 🤔

**Comment by 0xsarvesh** [comment] 2019-04-24 11:45
Refer this: 
https://github.com/OpenST/openst-contracts/blob/800b0d209e7cc164841b35720bd536fd6170c1f9/contracts/token/TokenRules.sol#L261


There is no  `onlyRule` modifier in`directTransfers`  TokenRules contract is a rule for direct transfer.

**Comment by 0xsarvesh** [comment] 2019-04-24 12:14
> Ah I get your question. What if we want to firewall direct transfers? I think that is not considered at the moment. @benjaminbollen / @pgev ? 🤔

@schemar 
Scenario 2 mentioned in the ticket description talks about this requirement. 🤔

**Comment by schemar** [comment] 2019-04-24 12:34
Ah sorry, I didn't write that clear enough. It is not about direct transfers, it is about transfers resulting from rules. I will update the description.

**Comment by deepesh-kn** [comment] 2019-05-16 07:10
All tickets in the epic are closed. Closing this epic

**Closed as completed by deepesh-kn** 2019-05-16 07:10 UTC
Labels: Epic
