### ISSUE TITLE
Research ExTx signed by Wallet Keys for Redemption

### ISSUE THREAD

**Issue by achirala** [OpenSTFoundation/openst-contracts#90] opened 2018-11-16 12:15 UTC
Edited after a chat with @pgev: 

ExTx add usability because the facilitator can pay gas (among possibly more reasons).
Please read and evaluate if Gnosis Safe's implementation of multi-sig paths using ExTx can be used for redemption via TokenHolder

**Comment by abhayks1** [comment] 2018-11-21 09:37
**Gnosis Safe Analysis**
 
- Executes a transaction confirmed by required number of owners and then refunds the account that submitted the transaction.

- Multiple owners signatures is presented together in a single ExTx signed by a single nonce.

- The fees are always transferred even if the user transaction fails. 

- datahash is derived from SAFE_TX_TYPEHASH.

- Wallet keys are recovered from ECRecover and checked if it’s already authorized.

- Introduction of "safeTxGas" Gas that should be used for the Safe transaction.

- Introduction of "refundReceiver" which is  address of receiver of gas payment (or 0 if tx.origin).

**Redemption Flow**

- It’s an ExTx transaction. Every required wallet signs the transaction.

- Facilitator collects all required wallets signatures and executes TH redeem method.

- In TH redeem method below verifications are done:
       - Number of signatures are equal to required number of wallets.
       - Loop iteration is done on required number of wallets and dataHash is constructed.
       - With ECRecover owner key is recovered. Verification is done if owner is authorized.
      - Nonce verification is done. Below has more details on nonce verification.

**Nonce Verification Approaches**

_Approach 1 - Introduce nonce per wallet_

- Each owner signs the transaction using their nonce.
- In TH redemption method, pass array of wallets and array of signatures as argument. Iteration is done on required number of wallets and using ECRecover each wallet key is received.

_Disadvantage_
Array of wallets needs to be there in TH redemption method.

_Approach 2 - Reuse MultiSigWallet contract transactionCount nonce_

- Using “transactionCount” nonce, all owners sign the  transaction.
- Owner key is recovered with ECRecover by constructing dataHash using current contract transactionCount nonce value.

_Disadvantage_

Signing and executing the redemption transaction is an async process. This approach will tightly bound “transactionCount” nonce ordering. i.e. Same “transactionCount” nonce used for singing should be used while executing. If after signing redemption transaction, any other transaction(e.g. addWallet) gets executed, then recovering  owner key will fail because “transactionCount” nonce has changed.

_Approach 3 - Introduce Redemption nonce_ in TH

- Every required wallet signs the transaction using redemption nonce.
- Iteration is done on required number of wallets and dataHash is constructed using redemption nonce.

_Disadvantage_

It adds complexity of maintaining a new redemption nonce in TH. 

_Open Discussion Points_

- How facilitator will collect all owner signatures to perform ExTx transaction.
- Do we need to refund gas to facilitator.
 
cc: @benjaminbollen @achirala

**Closed** 2018-12-18 10:50 UTC
Labels: v0.10.0
